package bloodtestschedulerpackage;

public class RegistrationGUI extends javax.swing.JFrame
{

    /**
     * Creates new form RegistrationGUI
     */
    public RegistrationGUI()
    {
        initComponents();
        setSize(500, 600);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        NameLabel = new javax.swing.JLabel();
        GPNameLabel = new javax.swing.JLabel();
        PriorityLabel = new javax.swing.JLabel();
        PriorityComboBox = new javax.swing.JComboBox<>();
        AgeLabel = new javax.swing.JLabel();
        ClinicNameLabel = new javax.swing.JLabel();
        ClinicNameTextField = new javax.swing.JTextField();
        NameTextField = new javax.swing.JTextField();
        AgeTextField = new javax.swing.JTextField();
        GPNameTextField = new javax.swing.JTextField();
        FromHospitalLabel = new javax.swing.JLabel();
        FromHospitalCheckBox = new javax.swing.JCheckBox();
        RegisterPatientButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NameLabel.setText("Name:");

        GPNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GPNameLabel.setText("GP name:");

        PriorityLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PriorityLabel.setText("Priority:");

        PriorityComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PriorityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "Urgent" }));
        PriorityComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PriorityComboBoxActionPerformed(evt);
            }
        });

        AgeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AgeLabel.setText("Age:");

        ClinicNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ClinicNameLabel.setText("Clinic name:");

        ClinicNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ClinicNameTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ClinicNameTextFieldActionPerformed(evt);
            }
        });

        NameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NameTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                NameTextFieldActionPerformed(evt);
            }
        });

        AgeTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AgeTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AgeTextFieldActionPerformed(evt);
            }
        });

        GPNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GPNameTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                GPNameTextFieldActionPerformed(evt);
            }
        });

        FromHospitalLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FromHospitalLabel.setText("From Hospital:");

        FromHospitalCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FromHospitalCheckBox.setIconTextGap(6);

        RegisterPatientButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RegisterPatientButton.setText("REGISTER PATIENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegisterPatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GPNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClinicNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriorityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FromHospitalLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GPNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ClinicNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PriorityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(FromHospitalCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GPNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GPNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClinicNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClinicNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PriorityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PriorityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FromHospitalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(FromHospitalCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegisterPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PriorityComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PriorityComboBoxActionPerformed
    {//GEN-HEADEREND:event_PriorityComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriorityComboBoxActionPerformed

    private void ClinicNameTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ClinicNameTextFieldActionPerformed
    {//GEN-HEADEREND:event_ClinicNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClinicNameTextFieldActionPerformed

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_NameTextFieldActionPerformed
    {//GEN-HEADEREND:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void AgeTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AgeTextFieldActionPerformed
    {//GEN-HEADEREND:event_AgeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeTextFieldActionPerformed

    private void GPNameTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_GPNameTextFieldActionPerformed
    {//GEN-HEADEREND:event_GPNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GPNameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new RegistrationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField AgeTextField;
    private javax.swing.JLabel ClinicNameLabel;
    private javax.swing.JTextField ClinicNameTextField;
    private javax.swing.JCheckBox FromHospitalCheckBox;
    private javax.swing.JLabel FromHospitalLabel;
    private javax.swing.JLabel GPNameLabel;
    private javax.swing.JTextField GPNameTextField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JComboBox<String> PriorityComboBox;
    private javax.swing.JLabel PriorityLabel;
    private javax.swing.JButton RegisterPatientButton;
    // End of variables declaration//GEN-END:variables
}
